config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    mount RailsAdmin::Engine => "/admin", as: "rails_admin"
    post "/rate" => "rater#create", :as => "rate"
    root to: "pages#index"
    resources :mobiles
    resources :comments, only: [:create, :destroy]
    resources :makers
    resources :carts, except: [:show, :new, :edit]
    resources :orders, only: [:new, :create]
    get "/search" => "mobiles#search"
    resources :shops, only: :create
    post "/comment_children" => "comment_childrens#create"
    patch "/advertisement" => "advertisements#update"
    get "/orders/history" => "orders#history"
  end

  devise_for :users, controllers: { omniauth_callbacks: "user/omniauth_callbacks",
                                    registrations: "registrations" }
end

app/models/mobile.rb
class Mobile < ApplicationRecord
  ratyrate_rateable "quality"
  has_many :order_details, dependent: :destroy
  has_many :shop_mobiles, dependent: :destroy
  has_many :shops, through: :shop_mobiles
  has_many :comments, dependent: :destroy
  belongs_to :maker
  has_many :mobile_colors
  has_many :colors, through: :mobile_colors
  has_many :images, dependent: :delete_all
  accepts_nested_attributes_for :images, allow_destroy: true
  mount_uploader :avatar, AvatarUploader
  mount_uploader :hot_mobile, HotMobileUploader

  include PgSearch
  pg_search_scope :search_by_query,
                  against: [:name, :ram],
                  associated_against: {
                    maker: :name
                  },
                  using: {
                    tsearch: {
                      prefix: true
                    }
                  }

  scope :search_in_range, -> min, max do
    where("price >= ? AND price <= ?", min, max).order(price: :asc)
  end

  scope :desc_create_time, -> {order(created_at: :desc)}

  scope :recommend, -> mobile do
    where.not(id: mobile.id)
    .search_in_range(mobile.price - Settings.recommend.range,
                     mobile.price + Settings.recommend.range)
    .limit(Settings.recommend.limit)
  end

  scope :hot_mobile, -> do
    where(id: OrderDetail.select(:mobile_id).order("COUNT(*)").group(:mobile_id)
                                                              .limit(3))
  end

  def resolution
    resolution_width.to_s + "x" + resolution_height.to_s
  end

  def percent_sale_off
    if sale_time && sale_time > Time.now && older_price && older_price > price
      percent = ((older_price - price) * 100 / older_price).to_i
      "-#{percent}%"
    end
  end

  class << self
    def search params
      if params[:min].present? && params[:max].present? && params[:query].present?
       @mobiles = Mobile.search_by_query(params[:query])
                        .search_in_range(params[:min].to_i, params[:max].to_i)
                        .page params[:page]
      elsif params[:query].present?
        @mobiles = Mobile.search_by_query(params[:query]).page params[:page]
      elsif params[:min].present? && params[:max].present?
       @mobiles = Mobile.search_in_range(params[:min].to_i, params[:max].to_i)
                                         .page params[:page]
      else
        @mobiles = Mobile.all.page params[:page]
      end
    end
  end
end

app/controllers/mobiles_controller.rb
class MobilesController < ApplicationController
  before_action :load_mobile, only: :show
  load_and_authorize_resource

  def index
    @mobiles = SearchForm.new(params).search.page params[:page]
    @amount = @mobiles.size
    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  def search
    if params[:search].present?
      @mobiles = Mobile.search_by_query params[:search]
    end

    respond_to do |format|
      format.js
    end
  end

  def show
    @shop = Shop.new
    @comments = Comment.search_comments(params[:id], nil).page(params[:page]).per(
      Settings.kaminari.paginate_comment)
    @comment = @mobile.comments.build
    @recommends = Mobile.recommend @mobile
    gon.sale_time = @mobile.sale_time.to_s.gsub! '-', '/'
    respond_to do |format|
      format.html
      format.js {render layout: false}
    end
  end

  private

  def load_mobile
    @mobile = Mobile.find_by id: params[:id]
    return if @mobile
    redirect_to root_path
    flash[:danger] = t("flash.load_mobile") + params[:id]
  end
end

app/views/mobiles/_comment_form.html.erb
<div class="form-group well">
  <%= form_for @comment, remote: true do |f| %>
    <%= f.hidden_field :mobile_id %>
    <%= f.hidden_field :parent_id %>
    <%= f.text_area :content, class: "form-control", 
      placeholder: t("views.mobiles.show.comment_here") %><br/>
    <div class="submit-comment">
      <%= f.submit t("views.mobiles.show.submit"), 
        class: "btn btn-primary submit-comment-form" %>
    </div>
  <% end %>
</div>

app/views/mobiles/_mobile.html.erb
<% if @mobiles.present? %>
  <% @mobiles.each do |mobile| %>
  <div class="col-md-3 product-left">
    <div class="product-main simpleCart_shelfItem">
      <%= link_to image_tag("p-1.jpg", class: "img-responsive zoom-img"),
          mobile, class: "mask" %>
      <div class="product-bottom">
        <h3><%= mobile.name %></h3>
        <h4><a class="item_add" href="#"><i></i></a> <span class=" item_price"><%= number_with_delimiter mobile.price, delimiter: "," %>đ</span></h4>
      </div>
      <div class="srch">
        <span>-50%</span>
      </div>
    </div>
  </div>
  <% end %>
<% end %>

app/views/mobiles/_slide.html.erb
<li data-thumb="<%= asset_path slide.mobile_image.url %>">
  <div class="thumb-image">
    <%= image_tag slide.mobile_image.url, class: "img-responsive",
    "data-imagezoom": "true" %>
  </div>
</li>

app/views/mobiles/index.html.erb
<!--start-breadcrumbs-->
<div class="breadcrumbs">
  <div class="container">
    <div class="breadcrumbs-main">
      <ol class="breadcrumb">
        <li><%= link_to t("views.header.home"), root_path %></li>
        <li class="active"><%= t('views.search.search') %></li>
      </ol>
    </div>
  </div>
</div>
<!--end-breadcrumbs-->

<div class="product">
  <div class="container">
    <h4><%= t "views.search.amount", amount: @amount %></h4>
    <%= paginate(@mobiles, remote: true) if @mobiles.present? %>
    <div class="product-top">
      <div class="product-one">
        <% if @mobiles.present? %>
          <%= render partial: "shared/mobile", collection: @mobiles %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
</div>
<% if @cart.present? %>
  <%= render partial: "shared/cart", locals: {cart: @cart}%>
<% end %>

app/views/mobiles/index.js.erb
$('.product-one').html('<%= j raw(render 'mobile') %>');
$('.pagination').html('<%= j paginate(@mobiles, remote: true) %>');

app/views/mobiles/search.js.erb
<% if @mobiles.present? %>
  <% @mobiles[0..4].each_with_index do |mobile, index| %>
    $('<%= "#search-#{index} a" %>').attr('href', '<%= mobile_url mobile %>');
    $('<%= "#search-#{index} img" %>').attr('src', '<%= mobile.avatar %>');
    $('<%= "#search-#{index} span" %>').text('<%= mobile.name %>');
  <% end %>
<% else %>
  $('[data-toggle="popover"]').popover('hide');
<% end %>

app/views/mobiles/show.html.erb
<div class="breadcrumbs">
  <div class="container">
    <div class="breadcrumbs-main">
      <ol class="breadcrumb">
        <li><%= link_to t("views.carts.index.home"), root_path %></li>
        <li class="active"><%= t "views.carts.index.item" %></li>
      </ol>
    </div>
  </div>
</div>
<!--end-breadcrumbs-->
<!--start-single-->
<div class="single contact">
  <div class="container">
    <div class="single-main header-mobile-info">
      <div class="col-md-9 single-main-left">
        <div class="sngl-top">
          <div class="col-md-5 single-top-left">
            <div class="flexslider">
                <ul class="slides">
                  <%= render partial: "slide", collection: @mobile.images %>
                </ul>
            </div>
            <!-- FlexSlider -->
          </div>
          <div class="col-md-7 single-top-right">
            <div class="single-para simpleCart_shelfItem">
              <h2><%= @mobile.name %><%= social_share_button_tag(@mobile.name, desc: @mobile.name) %></h2>
              <div class="star-on">
                <div class="row">
                  <div class="col-md-7 rating-mobile">
                    <%= rating_for @mobile, "quality", star: 10, cancel: true, disable_after_rate: false %>
                  </div>
                  <div class="col-md-5">
                    <i href="#"> <%= @mobile.rates("quality").count %>&nbsp
                      <%= t "views.mobiles.show.customer_rating"%> </i>
                  </div>
                </div>
                <div class="clearfix"></div>
              </div><br/>
              <% if @mobile.percent_sale_off %>
                <span class="item_price price">
                  <span class="sale-label"><%= t "views.mobiles.show.older_price" %></span>
                  <span class="older-price sale">
                    <%= number_with_delimiter @mobile.older_price, delimiter: "," %>
                  </span>&nbsp<%= Settings.currency.vnd %>
                </span>
                <span class="sale sale-percent">&nbsp&nbsp<%= @mobile.percent_sale_off %></span>
                <br></br>
              <% end %>
              <span class="item_price price">
                <span class="sale-label"><%= t("views.mobiles.show.newer_price") if @mobile.percent_sale_off %></span>
                <span id="mobile-price-<%= @mobile.id %>" class="sale">
                  <%= number_with_delimiter @mobile.price, delimiter: "," %>
                </span><%= Settings.currency.vnd %>
              </span>
              <% if @mobile.percent_sale_off %>
                <p>
                  <b><%= t "views.mobiles.show.remaining" %></b>
                  <span class="sale" id="message-sale-off-product"></span>
                </p>
              <% end %>
              <br></br><hr></hr>
              <p><%= @mobile.description %></p>
              <div class="available">
                <%= form_for :cart, url: {controller: :carts, action: :create}, remote: true do |f|%>
                  <ul>
                    <%= f.hidden_field :mobile_id, value: @mobile.id %>
                    <li><%= f.label t "views.carts.index.color" %>
                      <%= select_tag "cart[color_id]", options_from_collection_for_select(@mobile.colors, "id", "color", "0"), {class: "form-control"} %>
                    </li>
                    <div class="clearfix"> </div>
                  </ul>
                  <%= f.label t "views.mobiles.show.quantity" %>
                  <%= f.number_field :quantity, class: "form-control", value: 1, min: 1 %><br/>
                  <%= f.submit t("views.mobiles.show.add_to_cart"), class: "btn btn-primary"%>
                <% end %>
              </div>
            </div>
          </div>
          <div class="clearfix"> </div>
        </div>
      </div>
      <div class="col-md-3 single-right">
        <div class="w_sidebar">
          <section  class="sky-form">
            <h4><%= t"views.mobiles.show.check_exit_mobile" %></h4>
              <div class="col col-4">
                <%= form_for @shop, remote: true do |f| %>
                  <%= f.hidden_field :mobile_id, value: @mobile.id %>
                  <%= f.label t("views.mobiles.show.city") %><br/>
                  <%= f.collection_select :city_id, City.order(:name), :id, :name, {include_blank: true},{class: "form-control"} %><br/>
                  <%= f.label t("views.mobiles.show.district")  %><br/>
                  <%= f.grouped_collection_select :district_id, City.order(:name), :districts, :name, :id, :name, {include_blank: true}, {class: "form-control"} %><br/>
                  <%= f.submit t("views.mobiles.show.check"), class: "btn btn-primary form-control" %>
                <% end %>
              </div>
              <ul class="col col-4 show-check-mobile"></ul>
          </section>
          <hr></hr>
          <div id="tabs">
            <h3><%= t "views.mobiles.show.specifications" %></h3>
            <table class="table">
              <tr>
                <td><%= t "views.mobiles.show.resolution" %></td>
                <td><%= @mobile.resolution %>&nbspPixels</td>
              </tr>
              <tr>
                <td><%= t "views.mobiles.show.size" %></td>
                <td><%= t "views.mobiles.show.height" %>:&nbsp<%= @mobile.height %>mm -
                <%= t "views.mobiles.show.weight" %>:&nbsp<%= @mobile.width %>mm</td>
              </tr>
              <tr>
                <td><%= t "views.mobiles.show.front_camera" %></td>
                <td><%= @mobile.front_camera %>&nbspMP</td>
              </tr>
              <tr>
                <td><%= t "views.mobiles.show.behind_camera" %></td>
                <td><%= @mobile.behind_camera %>&nbspMP</td>
              </tr>
              <tr>
                <td><%= t "views.mobiles.show.ram" %></td>
                <td><%= @mobile.ram %></td>
              </tr>
              <tr>
                <td><%= t "views.mobiles.show.battery" %></td>
                <td><%= @mobile.battery %>&nbspmAh</td>
              </tr>
            </table>
          </div>
        </div>
      </div>
      <div class="clearfix"> </div>
    </div>
    <div class="single-main">
      <div class="col-md-9 single-main-left">
        <div class="tabs">
        <%= raw @mobile.review %>
        <div class="comment-session">
          <h1><%= t "views.mobiles.show.comment" %></h1>
          <%= render "comment_form" %>
          <div class="comment-content">
            <div class= "comment">
              <%= comments_tree_for(@comments) %>
            </div>
            <p class="pagination">
              <%= link_to_next_page(@comments, t("views.mobiles.show.more_comment"), :remote => true) %>
            </p>
          </div>
        </div>
      </div>
      </div>
      <div class="col-md-3 single-right specifications">
        <h3 class="text-center"><%= t "views.mobiles.show.recommend" %></h3>
        <% @recommends.each do |recommend| %>
          <div class="product-one">
            <div class="product-main simpleCart_shelfItem">
              <%= link_to mobile_path(recommend), class: "mark" do %>
                <%= image_tag recommend.avatar, class: "img-responsive zoom-img" %>
              <% end %>
              <div class="product-bottom">
                <h3 class= "mobile-name-<%= recommend.id %>"><%= recommend.name %></h3>
                <p><%= t "views.shared.explore_now" %></p>
                  <span class=" item_price">
                    <span id= "mobile-price-<%= recommend.id %>" value=<%= recommend.price %>>
                      <%=  number_with_delimiter recommend.price, delimiter: "," %>&nbsp<%= Settings.currency.vnd %></span>
                  </span>
                </h4>
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="form-group well" id="form_nested_comment" >
  <%= form_for @comment, remote: true do |f| %>
    <%= f.hidden_field :mobile_id, value: params[:id] %>
    <%= f.hidden_field :parent_id %>
    <%= f.text_area :content, class: "form-control", placeholder: t("views.mobiles.show.comment_here") %><br/>
    <div class="submit-comment">
      <%= f.submit t("views.mobiles.show.submit"), class: "btn btn-primary submit-comment-form" %>
    </div>
  <% end %>
</div>
<div id="position-cart">
  <% if @cart.present? %>
    <%= render partial: "shared/cart", locals: {cart: @cart}%>
  <% end %>
</div>

app/views/mobiles/show.js.erb
$("<%=j comments_tree_for(@comments) %>").appendTo($(".comment"));
<% if @comments.last_page? %>
  $('.pagination').html(I18n.t("flash.end_loading"));
<% else %>
  $('.pagination').html("<%=j link_to_next_page(@comments, t("views.mobiles.show.more_comment"), :remote => true) %>");
<% end %>