config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    mount RailsAdmin::Engine => "/admin", as: "rails_admin"
    post "/rate" => "rater#create", :as => "rate"
    root to: "pages#index"
    resources :mobiles
    resources :comments, only: [:create, :destroy]
    resources :makers
    resources :carts, except: [:show, :new, :edit]
    resources :orders, only: [:new, :create]
    get "/search" => "mobiles#search"
    resources :shops, only: :create
    post "/comment_children" => "comment_childrens#create"
    patch "/advertisement" => "advertisements#update"
    get "/orders/history" => "orders#history"
  end

  devise_for :users, controllers: { omniauth_callbacks: "user/omniauth_callbacks",
                                    registrations: "registrations" }
end

app/views/shared/_cart.html.erb
<%= link_to carts_path, class: "shopping-cart" do %>
  <div class="row">
    <div class="col-md-4">
      <i class="fa fa-3x fa-shopping-cart" aria-hidden="true"></i>
    </div>
    <div class="col-md-8">
      <strong><%= t "views.mobiles.show.cart_have" %></strong><br/>
      <strong><%= cart.count %>&nbsp<%= t "views.orders.new.item" %></strong>
    </div>
  </div>
<% end %>

app/views/shared/_mobile.html.erb
<div id="show-mobile-<%= mobile.id %>">
  <div class="col-md-3 product-left">
    <div class="product-main simpleCart_shelfItem">
      <%= link_to mobile_path(mobile), class: "mark" do %>
        <%= image_tag mobile.avatar, class: "img-responsive zoom-img" %>
      <% end %>
      <div class="product-bottom">
        <h3 class= "mobile-name-<%= mobile.id %>"><%= mobile.name %></h3>
        <p><%= t "views.shared.explore_now" %></p>
          <span class=" item_price">
            <span id= "mobile-price-<%= mobile.id %>" value=<%= mobile.price %>><%=  number_with_delimiter mobile.price, delimiter: "," %>&nbspVND</span>
          </span>
        </h4>
      </div>
      <% if mobile.percent_sale_off %>
        <div class="srch">
          <span class= "mobile-discount-<%= mobile.id %>"><%= mobile.percent_sale_off %></span>
        </div>
      <% end %>
    </div>
  </div>
</div>