config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    mount RailsAdmin::Engine => "/admin", as: "rails_admin"
    post "/rate" => "rater#create", :as => "rate"
    root to: "pages#index"
    resources :mobiles
    resources :comments, only: [:create, :destroy]
    resources :makers
    resources :carts, except: [:show, :new, :edit]
    resources :orders, only: [:new, :create]
    get "/search" => "mobiles#search"
    resources :shops, only: :create
    post "/comment_children" => "comment_childrens#create"
    patch "/advertisement" => "advertisements#update"
    get "/orders/history" => "orders#history"
  end

  devise_for :users, controllers: { omniauth_callbacks: "user/omniauth_callbacks",
                                    registrations: "registrations" }
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :create_new_cart
  
  def create
    session[:cart] = @new_cart.data
    respond_to do |format|
      format.js
    end
  end

  def update
    session[:cart] = @new_cart.update_cart
  end

  def destroy
    session[:cart] = @new_cart.delete_item
  end
  
  def index
    @mobiles = Mobile.find @cart.map{|cart| cart["mobile_id"]}
  end
  
  private
  
  def create_new_cart
    @new_cart = CartForm.new params[:cart], @cart
  end
end

app/helpers/cart_helper.rb
module CartHelper
  def find_exits_item cart, mobile_id
    cart.detect{|item| item["mobile_id"] == mobile_id}
  end
  
  def find_color_mobile cart, mobile_id
    Color.find_by(id: find_exits_item(cart, mobile_id)["color_id"]).color
  end
end

app/views/carts/_mobile.html.erb
<ul class="cart-header order-mobile-<%= mobile.id %>">
  <div class="close1" onclick="remove_item(this)" id=<%= mobile.id %>> </div>
    <li class="ring-in">
      <%= link_to mobile_path(mobile) do %>
        <%= image_tag mobile.avatar, class: "img-responsive" %>
      <% end %>
    </li>
    <li><span class="name"><%= mobile.name %></span>
      <%= select_tag mobile.id, options_from_collection_for_select(mobile.colors, "id", "color", find_exits_item(@cart, mobile.id.to_s)["color_id"]), {class: "color color-#{mobile.id}"}%>
    </li>
    <li><span class="cost">
      <input id=<%= mobile.id %> class="quantity form-control order-quantity-<%= mobile.id %>" type="number" min="1" style="width: 150px" value="<%= find_exits_item(@cart, mobile.id.to_s)["quantity"] %>"></span>
    </li>
    <li><span class="cost price"><%= mobile.price %>&nbspVND</span></li>
  <div class="clearfix"> </div>
</ul>

app/views/carts/create.js.erb
<% if @cart.present? %>
  $("#position-cart").html("<%= j render partial: 'shared/cart', locals: {cart: @cart} %>");
  alert(I18n.t("flash.add_to_cart"));
<% else %>
  alert(I18n.t("flash.failed_add_to_cart"));
<% end %>

app/views/carts/index.html.erb
<!--start-breadcrumbs-->
<div class="breadcrumbs">
  <div class="container">
    <div class="breadcrumbs-main">
      <ol class="breadcrumb">
        <li><%= link_to t("views.carts.index.home"), root_path %></li>
        <li class="active"><%= t "views.carts.index.shopping_cart" %></li>
      </ol>
    </div>
  </div>
</div>
<% if @cart.present? %>
  <!--end-breadcrumbs-->
  <!--start-ckeckout-->
  <div class="ckeckout">
    <div class="container">
      <div class="ckeck-top heading">
        <h2><%= t "views.carts.index.shopping_cart" %></h2>
      </div>
      <div class="ckeckout-top">
      <div class="cart-items">
        <h5><%= link_to t("views.carts.index.go_home"), root_path %></h5>
        <div class="in-check" >
          <ul class="unit">
            <li><span><%= t "views.carts.index.item" %></span></li>
            <li><span><%= t "views.carts.index.product_name" %></span></li>
            <li><span><%= t "views.carts.index.quantity" %></span></li>
            <li><span><%= t "views.carts.index.unit_price" %></span></li>
            <div class="clearfix"> </div>
          </ul>
          <%= render partial: "mobile", collection: @mobiles %>
          <ul class="cart-header">
              <li class="ring-in"></li>
              <li><span class="name"><%= t "views.carts.index.total_price" %></span></li>
              <li><span class="cost"></span></li>
              <li><span></span></li>
              <li><span class="cost total_price"></span></li>
            <div class="clearfix"> </div>
          </ul>
          <div class="col-md-9"></div>
          <div class="col-md-3">
            <%= link_to  t("views.carts.index.next"), new_order_path, class: "btn btn-primary next_order" %>
          </div>
        </div>
      </div>
     </div>
    </div>
  </div>
  <!--end-ckeckout-->
<% else %>
  <h1 class= "text-center"><%= t "views.carts.index.no_item" %></h1>
  <div class= "text-center"><%= link_to t("views.carts.index.back_home"), root_path, class: "text-center btn btn-primary" %></div>
<% end %>

<%= javascript_include_tag "cart" %>