config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    mount RailsAdmin::Engine => "/admin", as: "rails_admin"
    post "/rate" => "rater#create", :as => "rate"
    root to: "pages#index"
    resources :mobiles
    resources :comments, only: [:create, :destroy]
    resources :makers
    resources :carts, except: [:show, :new, :edit]
    resources :orders, only: [:new, :create]
    get "/search" => "mobiles#search"
    resources :shops, only: :create
    post "/comment_children" => "comment_childrens#create"
    patch "/advertisement" => "advertisements#update"
    get "/orders/history" => "orders#history"
  end

  devise_for :users, controllers: { omniauth_callbacks: "user/omniauth_callbacks",
                                    registrations: "registrations" }
end

app/views/layouts/_footer.html.erb
<div class="information">
  <div class="container">
    <div class="infor-top">
      <div class="col-md-3 infor-left">
        <h3>Follow Us</h3>
        <ul>
          <li><a href="#"><span class="fb"></span><h6>Facebook</h6></a></li>
          <li><a href="#"><span class="twit"></span><h6>Twitter</h6></a></li>
          <li><a href="#"><span class="google"></span><h6>Google+</h6></a></li>
        </ul>
      </div>
      <div class="col-md-3 infor-left">
        <h3><%= t "views.footer.contact" %></h3>
        <ul>
          <li><p><%= "#{t("views.footer.call_for_buy")}: #{Settings.contact.call_for_buy}" %></p></li>
          <li><p><%= "#{t("views.footer.call_to_complain")}: #{Settings.contact.call_to_complain}" %></p></li>
          <li><p><%= "#{t("views.footer.call_for_warranty")}: #{Settings.contact.call_for_warranty}" %></p></li>
          <li><p><%= "#{t("views.footer.technical_assistance")}: #{Settings.contact.technical_assistance}" %></p></li>
        </ul>
      </div>
      <% citys.each do |city| %>
        <div class="col-md-3 infor-left">
          <h3><%= city.name %></h3>
          <ul>
            <% city.shops.each do |shop| %>
              <li><p><%= link_to shop.address, google_map(shop.address), target: "_blank" %></p></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="footer">
  <div class="container">
    <div class="footer-top">
      <div class="col-md-6 footer-left">

        <select class="dropdown drop" onchange="location = this.value;">
          <option value="" class="label"><%= t ".language" %></option>
          <option value="/en">
            <%= t ".english" %>
          </option>
          <option value="/vi">
            <%= t ".vietnamese"%>
          </option>
        </select>
      </div>
      <div class="col-md-6 footer-right">
        <p>© 2015 Luxury Watches. All Rights Reserved | Design by  <a href="http://w3layouts.com/" target="_blank">W3layouts</a> </p>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header-bottom">
  <div class="container">
    <div class="header">
      <div class="row">
        <div class="col-md-9 header-left">
          <div class="top-nav">
            <div class="col-md-12">
              <ul class="memenu skyblue">
                <%= link_to image_tag("logo.png"), root_path, class: "header-logo" %>
                <li class="grid"><%= render "layouts/price_search" %></li>
                <li class="grid"><%= render "layouts/ram_search" %></li>
                <li class="grid"><%= render "layouts/maker_search" %></li>
                <% if user_signed_in? %>
                  <li class="grid"><%= render "layouts/profile" unless current_user.admin? %></li>
                  <li><%= link_to t("views.header.admin"), rails_admin.dashboard_path if current_user.admin? %></li>
                  <li><%= link_to t("views.header.sign_out"), destroy_user_session_path, method: :delete %></li>
                <% else %>
                  <li><%= link_to t("views.header.sign_in"), new_user_session_path %></li>
                  <li><%= link_to t("views.header.sign_up"), new_user_registration_path %></li>
                <% end %>
              </ul>
            </div>
          </div>
          <div class="clearfix"> </div>
        </div>
        <div class="col-md-3 header-right">
          <div class="search-bar" data-toggle="popover" data-placement="bottom">
            <%= form_tag mobiles_path, method: :get, autocomplete: :off do %>
              <%= text_field_tag "search", params[:search], placeholder: "Search..." %>
              <%= submit_tag value="" %>
            <% end %>
          </div>
        </div>
        <div class="clearfix"> </div>
      </div>
    </div>
  </div>
</div>


<%= render "layouts/mobile_search_list" %>

app/views/layouts/_maker_search.html.erb
<a href="#"><%= t "views.search.maker" %></a>
<div class="mepanel">
  <div class="row">
    <% makers.each do |maker| %>
      <div class="col1 me-one">
        <h4><%= link_to maker.name, mobiles_path(search: maker.name) %></h4>
        <ul>
          <li><%= link_to t("views.search.price.below_1_million"), mobiles_path(min: 0, max: 1000000, search: maker.name) %></li>
          <li><%= link_to t("views.search.price.from_to", min: 1, max: 3), mobiles_path(min: 1000000, max: 3000000, search: maker.name) %></li>
          <li><%= link_to t("views.search.price.from_to", min: 3, max: 5), mobiles_path(min: 3000000, max: 5000000, search: maker.name) %></li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_mobile_search_list.html.erb
<div id="mobile-search-list" class="hide">
  <ul class="wrap-suggestion">
    <% (0..4).each do |num| %>
      <li id="search-<%= num %>">
        <a href="#">
          <img src="#">
          <span><b></b></span>
        </a>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/_price_search.html.erb
<a href="#"><%= t "views.search.price.price" %></a>
<div class="mepanel">
  <div class="row">
    <div class="col1 me-one">
      <h4><%= t "views.search.price.cheap" %></h4>
      <ul>
        <li><%= link_to t("views.search.price.below_1_million"), mobiles_path(min: 0, max: 1000000) %></li>
        <li><%= link_to t("views.search.price.from_to", min: 1, max: 2), mobiles_path(min: 1000000, max: 2000000) %></li>
        <li><%= link_to t("views.search.price.from_to", min: 2, max: 3), mobiles_path(min: 2000000, max: 3000000) %></li>
      </ul>
    </div>
    <div class="col1 me-one">
      <h4><%= t "views.search.price.normal" %></h4>
      <ul>
        <li><%= link_to t("views.search.price.from_to", min: 3, max: 4), mobiles_path(min: 3000000, max: 4000000) %></li>
        <li><%= link_to t("views.search.price.from_to", min: 4, max: 5), mobiles_path(min: 4000000, max: 5000000) %></li>
        <li><%= link_to t("views.search.price.from_to", min: 5, max: 6), mobiles_path(min: 5000000, max: 6000000) %></li>
      </ul>
    </div>
    <div class="col1 me-one">
      <h4><%= t "views.search.price.high_level" %></h4>
      <ul>
        <li><%= link_to t("views.search.price.from_to", min: 3, max: 4), mobiles_path(min: 6000000, max: 7000000) %></li>
        <li><%= link_to t("views.search.price.from_to", min: 4, max: 5), mobiles_path(min: 7000000, max: 8000000) %></li>
        <li><%= link_to t("views.search.price.from_to", min: 5, max: 6), mobiles_path(min: 8000000, max: 9000000) %></li>
        <li><%= link_to t("views.search.price.over_9_million"), mobiles_path(min: 9000000, max: 10000000) %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_profile.html.erb
<a href="#"><%= t("views.header.profile") %></a>
<div class="mepanel">
  <div class="row">
    <div class="col1 me-one">
      <p><%= link_to t("views.header.edit"), edit_user_registration_path %></p>
    </div>
    <div class="col1 me-one">
      <p><%= link_to t("views.header.history"), orders_history_path %></p>
    </div>
  </div>
</div>

app/views/layouts/_ram_search.html.erb
<a href="#">Ram</a>
<div class="mepanel">
  <div class="row">
    <div class="col1 me-one">
      <p><%= link_to "2 GB", mobiles_path(search: "2GB") %></p>
    </div>
    <div class="col1 me-one">
      <p><%= link_to "3 GB", mobiles_path(search: "3GB") %></p>
    </div>
    <div class="col1 me-one">
      <p><%= link_to "4 GB", mobiles_path(search: "4GB") %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MobileWorld</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= include_gon(init: true) %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="<%= image_path("favicon.ico") %>" rel="shortcut icon" />
    <script type="text/javascript">
      I18n.defaultLocale = "<%= I18n.default_locale %>";
      I18n.locale = "<%= I18n.locale %>";
    </script>
  </head>
  <body>
    <%= render "layouts/header"%>
    <div class="container">
      <% if flash %>
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= flash_class message_type %>">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong><%= message %></strong>
          </div>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer"%>
    <a id="back-to-top" href="#" class="btn btn-primary btn-lg back-to-top"
      role="button" data-toggle="tooltip" data-placement="left">
      <i class="fa fa-angle-double-up fa-1x"></i>
    </a>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>